apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin
  JWT_SECRET_KEY: 9f9d2f0c2f8d47d9b681b1c0a44f1b5f-local-assessment-secret
